package api

import ()

const (
	API_ERROR_SUCCESS = iota
	API_ERROR_BAD_REQUEST
	API_ERROR_FILE_SAVE_FAILED
	API_ERROR_FILE_NOT_FOUND
	API_ERROR_FILE_DATABASE_FAILED
	API_ERROR_BAD_AUTHENTICATION
	API_ERROR_PASSWORDS_DONT_MATCH
	API_ERROR_USER_ALREADY_EXISTS
	API_ERROR_SERVER_INFO_FAILED
)
